name: Releases

on:
  push:
    tags:
      - "feature_artifacts-helper_*"

jobs:
  build:
    runs-on: ubuntu-latest

    run:
      working-directory: src/artifacts-helper/codespaces_artifacts_helper_keyring

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: wntrblm/nox@main
        with:
          python-versions: "3.11, 3.12"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          version: "2.15.1"
          python-version-file: "src/artifacts-helper/codespaces_artifacts_helper_keyring/pyproject.toml"

      - name: Run nox release
        run: pdm release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: codespaces_artifacts_helper_keyring
          path: |
            src/artifacts-helper/codespaces_artifacts_helper_keyring/dist

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "src/artifacts-helper/codespaces_artifacts_helper_keyring/dist/codespaces_artifacts_helper_keyring-*"
          artifactErrorsFailBuild: true
          body: |
            Release notes go here
