name: CI

on:
  push:
    paths:
      - ".github/workflows/test-keyring.yaml"
      - "src/artifacts-helper/codespaces_artifacts_helper_keyring/**.py"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/test-keyring.yaml"
      - "src/artifacts-helper/codespaces_artifacts_helper_keyring/**.py"

defaults:
  run:
    working-directory: src/artifacts-helper/codespaces_artifacts_helper_keyring

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    outputs:
      session: ${{ steps.set-matrix.outputs.session }}
    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@main
      - id: set-matrix
        shell: bash
        run: echo session=$(nox --json -l | jq -c '[.[].session]') | tee --append $GITHUB_OUTPUT

  checks:
    name: Session ${{ matrix.session }}
    needs: [generate-jobs]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.generate-jobs.outputs.session) }}
    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@main
      - run: nox -s "${{ matrix.session }}"
